# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

env:
  SOURCE_DIR:
  TARGET_DIR:
  SCRIPT_DIR:
  PROJECT_DIR:

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
