version: '3.8'

services:
  # Default builder for both platforms
  umdoc-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/output
    command: >
      bash -c "mkdir -p /output && 
              if [ -f /build/umdoc/build-linux/umdoc ]; then 
                cp /build/umdoc/build-linux/umdoc /output/umdoc-linux && 
                echo 'Linux executable copied to output directory.'; 
              fi && 
              if [ -f /build/umdoc/build-windows/umdoc.exe ]; then 
                cp /build/umdoc/build-windows/umdoc.exe /output/umdoc-windows.exe && 
                echo 'Windows executable copied to output directory.'; 
              else 
                echo 'Warning: Windows build failed, but Linux build may be available.'; 
              fi"

  # Linux-only builder
  linux-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/output
    command: >
      bash -c "cp /build/umdoc/build-linux/umdoc /output/umdoc-linux &&
              echo 'Linux build completed. Executable copied to output directory.'"
    profiles: ["linux-only"]

  # Windows-only builder
  windows-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/output
    command: >
      bash -c "cp /build/umdoc/build-windows/umdoc.exe /output/umdoc-windows.exe &&
              echo 'Windows build completed. Executable copied to output directory.'"
    profiles: ["windows-only"]
    
  # Interactive shell for debugging
  shell:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/output
    command: bash
    stdin_open: true
    tty: true
    profiles: ["debug"]